<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class UserDay extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'date', 'user_id'
    ];

    protected $dates = [
        'date'
    ];

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['title'] = $this->date->format('d.m.Y');
        return $array;
    }
}
